# docker-compose.yaml
version: '3.8'
services:
 jenkins:
  image: jenkins/jenkins:lts
  privileged: true
  user: root
  ports:
    - 8080:8080
    - 50000:50000
  container_name: jenkins
  volumes:
    - /JenkinsProject/jenkins_compose/jenkins_configuration:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
 agent:
  image: jenkins/ssh-agent:jdk11
  privileged: true
  user: root
  container_name: agent
  expose:
    - 22
  environment:
    - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBs9JFsuNG7eFUd+l8tKWq2vIm9vBarLTdUA5r1TJ6o0 Daniel.Ens@DGMZ-NB-T14-5
